execute_process(COMMAND bash -c "git tag | head -n1 | cut -d. -f1"
    OUTPUT_VARIABLE VERSION_MAJOR)

execute_process(COMMAND bash -c "git tag | head -n1 | cut -d. -f2"
    OUTPUT_VARIABLE VERSION_MINOR
    ERROR_QUIET)

execute_process(COMMAND bash -c "git tag | head -n1 | cut -d. -f3"
    OUTPUT_VARIABLE VERSION_PATCH
    ERROR_QUIET)

execute_process(COMMAND git describe --tag --dirty
    OUTPUT_VARIABLE VERSION_STRING
    ERROR_QUIET)

string(STRIP "${VERSION_MAJOR}" VERSION_MAJOR)
string(STRIP "${VERSION_MINOR}" VERSION_MINOR)
string(STRIP "${VERSION_PATCH}" VERSION_PATCH)
string(STRIP "${VERSION_STRING}" VERSION_STRING)

set(VERSION "#ifndef WIC64_VERSION_H
#define WIC64_VERSION_H

/* This file is autogenerated, do not edit */

#include <cstdint>

#define WIC64_VERSION_MAJOR ${VERSION_MAJOR}
#define WIC64_VERSION_MINOR ${VERSION_MINOR}
#define WIC64_VERSION_PATCH ${VERSION_PATCH}
#define WIC64_VERSION_STRING \"${VERSION_STRING}\"

#endif // WIC64_SERVER_H")


if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/wic64/version.h)
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/wic64/version.h VERSION_)
else()
    set(VERSION_ "")
endif()

if (NOT "${VERSION}" STREQUAL "${VERSION_}")
    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/wic64/version.h "${VERSION}")
endif()