execute_process(COMMAND bash -c "git tag | head -n1 | cut -d. -f1"
    OUTPUT_VARIABLE VERSION_MAJOR)

execute_process(COMMAND bash -c "git tag | head -n1 | cut -d. -f2"
    OUTPUT_VARIABLE VERSION_MINOR
    ERROR_QUIET)

execute_process(COMMAND bash -c "git tag | head -n1 | cut -d. -f3"
    OUTPUT_VARIABLE VERSION_PATCH
    ERROR_QUIET)

execute_process(COMMAND git describe --tag --dirty
    OUTPUT_VARIABLE VERSION_STRING
    ERROR_QUIET)

string(STRIP "${VERSION_MAJOR}" VERSION_MAJOR)
string(STRIP "${VERSION_MINOR}" VERSION_MINOR)
string(STRIP "${VERSION_PATCH}" VERSION_PATCH)
string(STRIP "${VERSION_STRING}" VERSION_STRING)

set(VERSION "/* This file is autogenerated, do not edit */
#include <cstdint>

const uint8_t WIC64_VERSION_MAJOR = ${VERSION_MAJOR};
const uint8_t WIC64_VERSION_MINOR = ${VERSION_MINOR};
const uint8_t WIC64_VERSION_PATCH = ${VERSION_PATCH};
const char* WIC64_VERSION_STRING = \"${VERSION_STRING}\";")


if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/wic64/version.cpp)
    file(READ ${CMAKE_CURRENT_SOURCE_DIR}/wic64/version.cpp VERSION_)
else()
    set(VERSION_ "")
endif()

if (NOT "${VERSION}" STREQUAL "${VERSION_}")
    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/wic64/version.cpp "${VERSION}")
endif()